namespace WebAppBusMVC.WEB.Models
{
	public class InAddAsientosViewModel
	{
        public string? check_1 { get; set; }
        public decimal CostoAsiento_1 { get; set; }        
        public string? check_2 { get; set; }
        public decimal CostoAsiento_2 { get; set; }
        public string? check_3 { get; set; }
        public decimal CostoAsiento_3 { get; set; }
        public string? check_4 { get; set; }
        public decimal CostoAsiento_4 { get; set; }
        public string? check_5 { get; set; }
        public decimal CostoAsiento_5 { get; set; }
        public string? check_6 { get; set; }
        public decimal CostoAsiento_6 { get; set; }
        public string? check_7 { get; set; }
        public decimal CostoAsiento_7 { get; set; }
        public string? check_8 { get; set; }
        public decimal CostoAsiento_8 { get; set; }
        public string? check_9 { get; set; }
        public decimal CostoAsiento_9 { get; set; }
        public string? check_10 { get; set; }
        public decimal CostoAsiento_10 { get; set; }

        public string? check_11 { get; set; }
        public decimal CostoAsiento_ { get; set; }
        public string? check_12 { get; set; }
        public decimal CostoAsiento_12 { get; set; }
        public string? check_13 { get; set; }
        public decimal CostoAsiento_13 { get; set; }
        public string? check_14 { get; set; }
        public decimal CostoAsiento_14 { get; set; }
        public string? check_15 { get; set; }
        public decimal CostoAsiento_15 { get; set; }
        public string? check_16 { get; set; }
        public decimal CostoAsiento_16 { get; set; }
        public string? check_17 { get; set; }
        public decimal CostoAsiento_17 { get; set; }
        public string? check_18 { get; set; }
        public decimal CostoAsiento_18 { get; set; }
        public string? check_19 { get; set; }
        public decimal CostoAsiento_19 { get; set; }
        public string? check_20 { get; set; }
        public decimal CostoAsiento_20 { get; set; }
     
        public string? check_21 { get; set; }
        public decimal CostoAsiento_21 { get; set; }
        public string? check_22 { get; set; }
        public decimal CostoAsiento_22 { get; set; }
        public string? check_23 { get; set; }
        public decimal CostoAsiento_23 { get; set; }
        public string? check_24 { get; set; }
        public decimal CostoAsiento_24 { get; set; }
        public string? check_25 { get; set; }
        public decimal CostoAsiento_25 { get; set; }
        public string? check_26 { get; set; }
        public decimal CostoAsiento_26 { get; set; }
        public string? check_27 { get; set; }
        public decimal CostoAsiento_27 { get; set; }
        public string? check_28 { get; set; }
        public decimal CostoAsiento_28 { get; set; }
        public string? check_29 { get; set; }
        public decimal CostoAsiento_29 { get; set; }
        public string? check_30 { get; set; }
        public decimal CostoAsiento_30 { get; set; }

        public string? check_31 { get; set; }
        public decimal CostoAsiento_31 { get; set; }
        public string? check_32 { get; set; }
        public decimal CostoAsiento_32 { get; set; }
        public string? check_33 { get; set; }
        public decimal CostoAsiento_33 { get; set; }
        public string? check_34 { get; set; }
        public decimal CostoAsiento_34 { get; set; }
        public string? check_35 { get; set; }
        public decimal CostoAsiento_35 { get; set; }
        public string? check_36 { get; set; }
        public decimal CostoAsiento_36 { get; set; }
        public string? check_37 { get; set; }
        public decimal CostoAsiento_37 { get; set; }
        public string? check_38 { get; set; }
        public decimal CostoAsiento_38 { get; set; }
        public string? check_39 { get; set; }
        public decimal CostoAsiento_39 { get; set; }
        public string? check_40 { get; set; }
        public decimal CostoAsiento_40 { get; set; }

        public string? check_41 { get; set; }
        public decimal CostoAsiento_41 { get; set; }
        public string? check_42 { get; set; }
        public decimal CostoAsiento_42 { get; set; }
        public string? check_43 { get; set; }
        public decimal CostoAsiento_43 { get; set; }
        public string? check_44 { get; set; }
        public decimal CostoAsiento_44 { get; set; }
        public string? check_45 { get; set; }
        public decimal CostoAsiento_45 { get; set; }
        public string? check_46 { get; set; }
        public decimal CostoAsiento_46 { get; set; }
        public string? check_47 { get; set; }
        public decimal CostoAsiento_47 { get; set; }
        public string? check_48 { get; set; }
        public decimal CostoAsiento_48 { get; set; }
        public string? check_49 { get; set; }
        public decimal CostoAsiento_49 { get; set; }
        public string? check_50 { get; set; }
        public decimal CostoAsiento_50 { get; set; }

        public string? check_51 { get; set; }
        public decimal CostoAsiento_51 { get; set; }
        public string? check_52 { get; set; }
        public decimal CostoAsiento_52 { get; set; }
        public string? check_53 { get; set; }
        public decimal CostoAsiento_53 { get; set; }
        public string? check_54 { get; set; }
        public decimal CostoAsiento_54 { get; set; }
        public string? check_55 { get; set; }
        public decimal CostoAsiento_55 { get; set; }
        public string? check_56 { get; set; }
        public decimal CostoAsiento_56 { get; set; }
        public string? check_57 { get; set; }
        public decimal CostoAsiento_57 { get; set; }
        public string? check_58 { get; set; }
        public decimal CostoAsiento_58 { get; set; }
        public string? check_59 { get; set; }
        public decimal CostoAsiento_59 { get; set; }
        public string? check_60 { get; set; }
        public decimal CostoAsiento_60 { get; set; }

        public string? check_61 { get; set; }
        public decimal CostoAsiento_61 { get; set; }
        public string? check_62 { get; set; }
        public decimal CostoAsiento_62 { get; set; }
        public string? check_63 { get; set; }
        public decimal CostoAsiento_63 { get; set; }
        public string? check_64 { get; set; }

        public decimal CostoAsiento_64 { get; set; }
        public string? check_65 { get; set; }
        public decimal CostoAsiento_65 { get; set; }
        public string? check_66 { get; set; }
        public decimal CostoAsiento_66 { get; set; }
        public string? check_67 { get; set; }
        public decimal CostoAsiento_67 { get; set; }
        public string? check_68 { get; set; }
        public decimal CostoAsiento_68 { get; set; }
        public string? check_69 { get; set; }
        public decimal CostoAsiento_69 { get; set; }
        public string? check_70 { get; set; }
        public decimal CostoAsiento_70 { get; set; }

        public string? check_71 { get; set; }
        public decimal CostoAsiento_71 { get; set; }
        public string? check_72 { get; set; }
        public decimal CostoAsiento_72 { get; set; }
        public string? check_73 { get; set; }
        public decimal CostoAsiento_73 { get; set; }
        public string? check_74 { get; set; }
        public decimal CostoAsiento_74 { get; set; }
        public string? check_75 { get; set; }
        public decimal CostoAsiento_75 { get; set; }
        public string? check_76 { get; set; }
        public decimal CostoAsiento_76 { get; set; }
        public string? check_77 { get; set; }
        public decimal CostoAsiento_77 { get; set; }
        public string? check_78 { get; set; }
        public decimal CostoAsiento_78 { get; set; }
        public string? check_79 { get; set; }
        public decimal CostoAsiento_79 { get; set; }
        public string? check_80 { get; set; }
        public decimal CostoAsiento_80 { get; set; }

    }
}
